configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore src/SocketIO.Emitter.sln

build:
  project: src/SocketIO.Emitter.sln       
  verbosity: minimal
test:
  assemblies:
    - '**\*.Tests.dll'
